main:
  WANDB_PROJECT: "mlops-diabetic-readmission"
  WANDB_ENTITY: "fjsuarez-ie-university"
  MLFLOW_TRACKING_URI: "http://localhost:5000"
  MLFLOW_EXPERIMENT_NAME: "diabetic-readmission-pipeline"

data_source:
  raw_path: "./data/raw/diabetic_readmission_data.csv"
  type: "csv"
  delimiter: ","
  header: 0
  encoding: "utf-8"

data_load:
  data_stage: "raw"
  log_sample_artifacts: true
  log_summary_stats: true
  log_artifacts: true
  sample_size: 100
  
defaults:
  - _self_