main:
  WANDB_PROJECT: "mlops_pipeline"
  WANDB_ENTITY: "cameron-bell-ie"
  MLFLOW_TRACKING_URI: "http://localhost:5000"
  MLFLOW_EXPERIMENT_NAME: "diabetic-readmission-pipeline"
  steps: "all"
  hydra_options: ""

data_source:
  raw_path: "./data/raw/diabetic_readmission_data.csv"
  type: "csv"
  delimiter: ","
  header: 0
  encoding: "utf-8"
  keep_default_na: false
  na_values: ['']

data_load:
  log_sample_artifacts: true
  log_summary_stats: true
  log_artifacts: true

data_validation:
  enabled: true
  action_on_error: "raise"
  report_path: "logs/validation_report.json"
  schema:
    columns:
      - name: "encounter_id"
        dtype: "int"
        required: true
        min: 1
      - name: "patient_nbr"
        dtype: "int"
        required: true
        min: 1
      - name: "race"
        dtype: "str"
        required: false
        allowed_values: ["Caucasian", "AfricanAmerican", "Hispanic", "Asian", "Other", "?"]
      - name: "gender"
        dtype: "str"
        required: true
        allowed_values: ["Male", "Female", "Unknown/Invalid"]
      - name: "age"
        dtype: "str"
        required: true
        allowed_values: ["[0-10)", "[10-20)", "[20-30)", "[30-40)", "[40-50)", "[50-60)", "[60-70)", "[70-80)", "[80-90)", "[90-100)"]
      - name: "admission_type_id"
        dtype: "int"
        required: true
        min: 1
        max: 8
      - name: "discharge_disposition_id"
        dtype: "int"
        required: true
        min: 1
        max: 29
      - name: "admission_source_id"
        dtype: "int"
        required: true
        min: 1
        max: 25
      - name: "time_in_hospital"
        dtype: "int"
        required: true
        min: 1
        max: 14
      - name: "num_lab_procedures"
        dtype: "int"
        required: true
        min: 0
        max: 132
      - name: "num_procedures"
        dtype: "int"
        required: true
        min: 0
        max: 6
      - name: "num_medications"
        dtype: "int"
        required: true
        min: 1
        max: 81
      - name: "number_outpatient"
        dtype: "int"
        required: true
        min: 0
        max: 42
      - name: "number_emergency"
        dtype: "int"
        required: true
        min: 0
        max: 76
      - name: "number_inpatient"
        dtype: "int"
        required: true
        min: 0
        max: 21
      - name: "diag_1"
        dtype: "str"
        required: false
      - name: "diag_2"
        dtype: "str"
        required: false
      - name: "diag_3"
        dtype: "str"
        required: false
      - name: "number_diagnoses"
        dtype: "int"
        required: true
        min: 1
        max: 16
      - name: "max_glu_serum"
        dtype: "str"
        required: false
        allowed_values: ["None", ">200", ">300", "Norm", "?"]
      - name: "A1Cresult"
        dtype: "str"
        required: false
        allowed_values: ["None", ">7", ">8", "Norm", "?"]
      - name: "metformin"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "repaglinide"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "nateglinide"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "chlorpropamide"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "glimepiride"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "acetohexamide"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "glipizide"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "glyburide"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "tolbutamide"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "pioglitazone"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "rosiglitazone"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "acarbose"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "miglitol"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "troglitazone"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "tolazamide"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "insulin"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "glyburide-metformin"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "glipizide-metformin"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "glimepiride-pioglitazone"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "metformin-rosiglitazone"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "metformin-pioglitazone"
        dtype: "str"
        required: false
        allowed_values: ["No", "Down", "Steady", "Up", "?"]
      - name: "change"
        dtype: "str"
        required: true
        allowed_values: ["No", "Ch"]
      - name: "diabetesMed"
        dtype: "str"
        required: true
        allowed_values: ["No", "Yes"]
      - name: "readmitted"
        dtype: "str"
        required: true
        allowed_values: ["NO", "<30", ">30"]

preprocessing:
  enabled: true
  drop_columns: ['weight', 'payer_code', 'medical_specialty', 'examide', 'citoglipton']
  exclude_discharge_disposition: [11]  # Death
  na_indicators: ['?', 'Unknown/Invalid']

# ...existing config...

features:
  enabled: true
  medication_columns:
    - metformin
    - repaglinide
    - nateglinide
    - chlorpropamide
    - glimepiride
    - glipizide
    - glyburide
    - pioglitazone
    - rosiglitazone
    - acarbose
    - miglitol
    - insulin
    - glyburide-metformin
    - tolazamide
    - metformin-pioglitazone
    - metformin-rosiglitazone
    - glimepiride-pioglitazone
    - glipizide-metformin
    - troglitazone
    - tolbutamide
    - acetohexamide
  
  icd9_categories:
    Circulatory: [[390, 459], [785, 785]]
    Respiratory: [[460, 519], [786, 786]]
    Digestive: [[520, 579], [787, 787]]
    Diabetes: [[250, 250]]
    Injury: [[800, 999]]
    Musculoskeletal: [[710, 739]]
    Genitourinary: [[580, 629], [788, 788]]
    Neoplasms: [[140, 239]]
  
  value_mappings:
    admission_type_id: {2: 1, 7: 1, 6: 5, 8: 5}
    discharge_disposition_id: {6: 1, 8: 1, 9: 1, 13: 1, 3: 2, 4: 2, 5: 2, 14: 2, 22: 2, 23: 2, 24: 2, 12: 10, 15: 10, 16: 10, 17: 10, 25: 18, 26: 18}
    admission_source_id: {2: 1, 3: 1, 5: 4, 6: 4, 10: 4, 22: 4, 25: 4, 15: 9, 17: 9, 20: 9, 21: 9, 13: 11, 14: 11}
    binary_vars:
      change: {"Ch": 1, "No": 0}
      gender: {"Male": 1, "Female": 0}
      diabetesMed: {"Yes": 1, "No": 0}
    lab_tests:
      A1Cresult: {">7": 1, ">8": 1, "Norm": 0, "None": -99}
      max_glu_serum: {">200": 1, ">300": 1, "Norm": 0, "None": -99}
    age: {"[0-10)": 1, "[10-20)": 2, "[20-30)": 3, "[30-40)": 4, "[40-50)": 5, "[50-60)": 6, "[60-70)": 7, "[70-80)": 8, "[80-90)": 9, "[90-100)": 10}
    readmission: {">30": 0, "<30": 1, "NO": 0}
    medication_status: {"No": 0, "Steady": 1, "Up": 1, "Down": 1}