main:
  WANDB_PROJECT: "mlops_pipeline"
  WANDB_ENTITY: "cameron-bell-ie"
  MLFLOW_TRACKING_URI: "http://localhost:5000"
  MLFLOW_EXPERIMENT_NAME: "diabetic-readmission-pipeline"
  steps: "all"
  hydra_options: ""

data_source:
  raw_path: "./data/raw/diabetic_readmission_data.csv"
  type: "csv"
  delimiter: ","
  header: 0
  encoding: "utf-8"

data_load:
  log_sample_artifacts: true
  log_summary_stats: true
  log_artifacts: true